### ISSUE TITLE
feat: Cluster API support

### ISSUE THREAD

**Issue by lukasmrtvy** [apache/cloudstack-kubernetes-provider#37]
Would be superb to support also Cluster API https://github.com/kubernetes-sigs/cluster-api
OpenStack is already supported https://github.com/kubernetes-sigs/cluster-api-provider-openstack
Thanks

**Comment by rohityadavcloud** [comment]
@lukasmrtvy Thanks for the suggestion. Can you share more information about your use-case (e.g., what Kubernetes distribution you're using, K8s version, operating system, etc.)?

**Comment by memorais** [comment]
Hi, I'm trying to setup cloudstack-kubernetes-provider on a cluster created with cloudstack cluster-api provider. After install cloudstack-kubernetes-provider on that cluster, any scale up on machinedeployments results on the following scenario:

`I0224 18:19:01.882948       1 event.go:278] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"demo-md-0-cbh9n", UID:"8e3f0ee3-16d4-43ec-a855-1574a8117012", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Deleting node demo-md-0-cbh9n because it does not exist in the cloud provider' Node demo-md-0-cbh9n event: DeletingNode`

CCM delete the node that recently joined with that message "it does not exist in the cloud provider". Why it deletes the node, what that message specific means? There is any workaround for this?

Thanks.

**Comment by memorais** [comment]
As an workaround I revoke the "delete" verb on resource "nodes". CCM give up from delete the node after a while and everything work as expected. This seems some bug when listing nodes and joining new nodes on the cluster. If anyone have interest on solving that, I can provide steps to reproduce the problem.

**Comment by weizhouapache** [comment]
@memorais 
can you create new issues ?


CAPI cloudstack is here: https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack
